### PR TITLE
Add chord syncronisation from the database

### PR DESCRIPTION
**Pull request by AllexVeldman**
This tracks chord synchronisation in the ChordCounter model instead of using the polling `unlock_chord` task.
In general it keeps a counter of the size of the chord header and decrements this counter on each return.
When the counter hits 0 the callback is triggered (borrowed from `unlock_chord`)

relates to #52

### CODE REVIEW

**Comment by AllexVeldman** [comment]
Because the `select_for_update()` currently only has effect for postgresql, oracle and mysql this could potentially cause a race condition in the counter, should this behaviour be an option?

**Comment by AllexVeldman** [comment]
Failing tests due to issues solved in #141 and #139

**Comment by AllexVeldman** [comment]
@auvipy could you indicate if this is the correct approach?

**Comment by auvipy** [comment]
i will look into this next week

**Comment by ZviBaratz** [comment]
@auvipy @AllexVeldman Any updates on this?

**Comment by AllexVeldman** [comment]
I haven't received any feedback yet, have been using a very similar implementation for a while now and have not yet run into any issues.

**Comment by ZviBaratz** [comment]
Sounds good. @auvipy? 
Sorry for barging in here, just thought I'll check if I can do anything to help out. I :heart: Django + Celery.

**Comment by auvipy** [comment]
ops damn I missed it for so long

**Comment by auvipy** [comment]
> Sounds good. @auvipy?
> Sorry for barging in here, just thought I'll check if I can do anything to help out. I heart Django + Celery.

can you try this patch on your dev env?

**Comment by ZviBaratz** [comment]
> can you try this patch on your dev env?

I tried running the tests but I'm getting a bunch of unrelated errors due to the `celery.five` import call in `models.py` (also discussed in #157). I'll try and figure out what's going on there but I'm somewhat new to celery so the implications of the transition from v. 4 to 5 are somewhat beyond me.

**Comment by arnau126** [comment]
I've fixed this "unrelated errors" in PR: #163

**Review by auvipy — APPROVED** [review]

**Pull request merged**
