### PR TITLE
Add support for Celery>=5.0

### LINKED ISSUE #157: No module named celery.five
Celery 5.x remove the `celery.five` and drop support for python2:
``` 
 File "/home/qiaocc/.venv/devops_env/lib/python3.8/site-packages/django_celery_results/models.py", line 9, in <module>
    from celery.five import python_2_unicode_compatible
ModuleNotFoundError: No module named 'celery.five'
```
 `django-celery-results` can also drop the support for python2

### PR DESCRIPTION
**Pull request by mondeja**
- `celery.five` module is removed in Celery 5.0, so I've removed it dropping support for Python2.
- Removed and reorder some arguments in docstrings.
- `flake8` version updated.
- `pytest` version updated.
- `pydocstyle` environment removed from `tox.ini` because of #139 (section maintained to test locally until the failure is properly handled).
- `apicheck` environment removed from `tox.ini` because of it was giving me next error that I can't able to handle:

```
Warning, treated as error:
/.../django-celery-results/django_celery_results/managers.py:docstring of django_celery_results.managers.TaskResultManager.store_result:4:Title underline too short.
```

In addition to this, the docstrings of the package needs to be unified following one style to make it work `pydocstyle` and `apicheck` without ignore half of the package (see `apicheck_ignore_modules` parameter in `docs/conf.py`), but this pull is more urgent.

Closes #157

### CODE REVIEW

**Comment by iMerica** [comment]
LGTM 👍.

**Comment by thedrow** [comment]
I'll try to review this as soon as possible.

**Comment by ZviBaratz** [comment]
Also replaced by #163 and can be closed?

**Comment by auvipy** [comment]
closing as per another merged PR

**Pull request closed without merging**
