### PR TITLE
Fix group id in migration

### PR DESCRIPTION
**Pull request by tomwojcik**
fix mig default value

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Review by auvipy — CHANGES_REQUESTED** [review]
>           raise self.model.DoesNotExist(

                "%s matching query does not exist." %

                self.model._meta.object_name

            )

E           django_celery_results.models.ChordCounter.DoesNotExist: ChordCounter matching query does not exist.

**Comment by tomwojcik** [comment]
@auvipy yes yes, I'm on it. When I had a moment I didn't manage to setup the test env. Will try later this week.

**Comment by auvipy** [comment]
ping

**Comment by tomwojcik** [comment]
Sorry but I don't understand what the issue is and I can't seem to setup the test env.

**Pull request closed without merging**
