### PR TITLE
added task name to TaskResult

### PR DESCRIPTION
**Pull request by stuartaccent**
As per request, I have been asked to pr this, if you want me to do anything else with this please shout

Stu :)

### CODE REVIEW

**Comment by stuartaccent** [comment]
Have also been asked to add the foreign key of the task. Am not sure what others think of this but for me it holds little value, all I need to know is the task name it came from.

What if i delete the task does it need to cascade? 
I would not want it to remove the results but would not want to loose the info about where it came from.

What if the task did not originate from the model itself? should it not store anything? 
Maybe the foreign key is in addition to the name.

I dont want to overcomplicate what is a very simple solution to get to the desired result.

Stu

**Comment by crutcha** [comment]
Any idea if/when this PR will be merged in? Been looking for this functionality and stumbled across this and it would be extremely useful.

**Comment by grafa** [comment]
Hey there I hope anyone from Celery team actually reads this message. Can you please give this pull requests the green card? It's been 1.5 year since @stuartaccent made his homework and all checks has passed.

Pretty please :crying_cat_face:

**Comment by stuartaccent** [comment]
I will look at fixing the conflicts IF anyone says they r willing to merge it :)

**Comment by wardal** [comment]
@grafa similar pr was merged already https://github.com/celery/django-celery-results/pull/34

**Comment by crutcha** [comment]
Ah indeed it was, but still not released into PyPi.

**Comment by thedrow** [comment]
Since this is a duplicate of #34 I'm going to close it.
Thanks for the contribution!

**Pull request closed without merging**
