### PR TITLE
Revert "feat: raw delete expired instead of `Queryset.delete` (#235)"

### PR DESCRIPTION
**Pull request by hansegucker**
This partially reverts commit 7c7cb67fb818b7e37dbb8e7ad52ec8ce6f2faada as recommended in https://github.com/celery/django-celery-results/pull/235#issuecomment-1385032707. This also fixes https://github.com/celery/django-celery-results/issues/383.

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
can you please check the CI failures?

**Comment by hansegucker** [comment]
> can you please check the CI failures?

The fix for the CI failure is in https://github.com/celery/django-celery-results/pull/382 (at least partially). The full fix can be found in the latest commit of this PR.

**Comment by hansegucker** [comment]
Please rerun CI with current changes.

**Comment by auvipy** [comment]
we have only one test to fix
 =========================== short test summary info ============================
ERROR t/unit/test_migrations.py::MigrationTests::test_models_match_migrations

**Review by auvipy — APPROVED** [review]

**Comment by hansegucker** [comment]
I would be perfect if we can get a new release with this fix.

**Comment by auvipy** [comment]
ping me next week

**Comment by hansegucker** [comment]
@auvipy ping

**Comment by auvipy** [comment]
Ping again tomorrow please!

**Comment by hansegucker** [comment]
@auvipy ping again

**Comment by hansegucker** [comment]
@auvipy ping, ping ;-)

**Comment by auvipy** [comment]
sorry forgot about it with other priorities!

**Comment by auvipy** [comment]
I am sorry for the delay. there are lots of other things to look after so!

**Pull request merged**
