### PR TITLE
Fix max_length of group_id in 0008_chordcounter migration

### LINKED ISSUE #167: Invalid migration value for `max_length` ChordCounter.group_id on master
I use this lib from commit ed94080cea3d68a38f9ff048657a37b08e74fc35 with fixes for Celery 5.x 

After making migrations it adds.

```
Migrations for 'django_celery_results':
  /usr/local/lib/python3.8/site-packages/django_celery_results/migrations/0009_auto_20201021_1026.py
    - Alter field group_id on chordcounter
```

https://github.com/celery/django-celery-results/commit/ed94080cea3d68a38f9ff048657a37b08e74fc35#diff-fb5af8c04137d0318c8f7a50ddb6697523e311bf7773374ff886817027a657e6R116-R125

vs

https://github.com/celery/django-celery-results/commit/ed94080cea3d68a38f9ff048657a37b08e74fc35#diff-e1f276feafdcddf6dc83ab6214d028c3d98008407e4320bd479d6c69d427dd48R22-R27

### PR DESCRIPTION
**Pull request by arnau126**
Fix 0008_chordcounter migration: use DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH in the max_length of group_id.

It fixes #167 .

### CODE REVIEW

**Review by auvipy — APPROVED** [review]

**Review by auvipy — CHANGES_REQUESTED** [review]
tests are failing https://travis-ci.org/github/celery/django-celery-results/jobs/741157236

**Comment by arnau126** [comment]
I've added a new commit to fix test failures, but the jobs from the previous commit are still running (waiting to start, actually).
Is there any way to cancel them, so the ones from the new commit can be executed promptly?
Thanks

**Comment by arnau126** [comment]
I would like you to consider these options: https://docs.travis-ci.com/user/customizing-the-build#building-only-the-latest-commit. Thanks

**Comment by arnau126** [comment]
I'm not sure why tests are failing. The error is:
```
E           django.db.utils.OperationalError: could not connect to server: No such file or directory
E           	Is the server running locally and accepting
E           	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
So, it seems a postgresql related error.

I'm comparing [the failing job of this PR](https://travis-ci.org/github/celery/django-celery-results/jobs/741212399) with the last [successful job](https://travis-ci.org/github/celery/django-celery-results/jobs/738033848), and the only significant difference that I see in job logs is:

**Successful job:**
> 88 | `psql (PostgreSQL) 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1)` in the successful job

> 171 | $ travis_setup_postgresql
> 172 | Starting PostgreSQL v12
> 173 | sudo systemctl start postgresql@12-main


**Failing job**:
> 88 | `psql (PostgreSQL) 13.0 (Ubuntu 13.0-1.pgdg20.04+1)` and

> 172 | $ travis_setup_postgresql
> 173 | Starting PostgreSQL v12
> 174 |  **Assertion failed on job for postgresql@12-main.service.**
> 175 | sudo systemctl start postgresql@12-main

So the problem might be the new PostgreSQL 13, which was released a month ago (2020-09-24).
But I don't know why the successful job (from 2020-10-22) used PostgreSQL 12, and the failing job (from 2020-11-03) uses PostgreSQL 13.

**Comment by arnau126** [comment]
Same issue here: https://travis-ci.community/t/postgresql-broken-on-focal/10371 . 
The fix proposed by @jasiekmarc also works here.

**Comment by arnau126** [comment]
@auvipy , I've added a commit with the changelog for 2.0.0. Feel free to rephrase any sentence.

**Review by auvipy — APPROVED** [review]

**Pull request merged**
