### PR TITLE
feat: add periodic_task_name

### PR DESCRIPTION
**Pull request by lvelvee**
#253

### CODE REVIEW

**Comment by lvelvee** [comment]
related: https://github.com/lvelvee/django-celery-beat/tree/feat-periodic-task-name

**Review by auvipy — CHANGES_REQUESTED** [review]
please check the test failures

**Comment by auvipy** [comment]
some documentation change is require i guess

**Comment by auvipy** [comment]
I am curious what extra benefits we get by adding this? what the existing 2 packages are missing?

**Comment by lvelvee** [comment]
> I am curious what extra benefits we get by adding this? what the existing 2 packages are missing?

If a `CeleryTask` may correspond to more than one `PeriodicTask`, it will not be possible to distinguish the source of the `PeriodicTask` because django-celery-results lacks the name field of the `PeriodicTask`.

For example, if I have two `PeriodicTask` named `periodic_a` and `periodic_b`, both of which call the `test` task of celery at regular intervals, without this patch, the results will only be known as the results of `test`, and there will be no way to distinguish whether the task originated from `periodic_a` or `periodic_b`.

**Comment by lvelvee** [comment]
@auvipy Is it still possible to be merged?

**Review by auvipy — APPROVED** [review]
i guess some change in celery beat is also required?

**Comment by lvelvee** [comment]
I'll make the pr later

**Pull request merged**
