### PR TITLE
Added missing migrations - Fixes #210

### LINKED ISSUE #210: Incorrect migrations in 2.1.0
Not all migrations included in package, that's why any 'no migration' CI/CD will fail.

Like example:

```
$ docker-compose -f docker-compose.dev.yml exec -T django python manage.py makemigrations --check
Migrations for 'django_celery_results':
  /usr/local/lib/python3.9/site-packages/django_celery_results/migrations/0010_auto_20210615_2047.py
    - Alter field group_id on chordcounter
    - Alter field group_id on groupresult
    - Alter field task_id on taskresult
```

### PR DESCRIPTION
**Pull request by jspitzen**

### CODE REVIEW

**Comment by auvipy** [comment]
@AllexVeldman

**Review by AllexVeldman — CHANGES_REQUESTED** [review]
This fixes the max_length to the default of DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH (255), not actually respecting the setting.

**Comment by AllexVeldman** [comment]
See #207

**Comment by auvipy** [comment]
all the tests are failing

**Comment by AllexVeldman** [comment]
> all the tests are failing

@auvipy i think this PR is not needed, see my comments in #210

**Comment by jspitzen** [comment]
I agree, I was just trying a quick-fix.

**Pull request closed without merging**
