### PR TITLE
Store task name, args and kwargs in db and show in admin panel

### PR DESCRIPTION
**Pull request by wardal**
Store task name, args and kwargs in db and show in admin panel https://github.com/celery/django-celery-results/issues/7

### CODE REVIEW

**Comment by ShaheedHaque** [comment]
Do we know if there is any plan to merge this (and it's filter friend)?

Or even one of the several variations? It would seem that would solve several open issues and PRs.

**Comment by thedrow** [comment]
Sorry, I did not get to review this earlier.

**Comment by kennydude** [comment]
Would it be possible to get this into a release on PyPi?

**Comment by rathish** [comment]
Hi, I believe this is not yet released in PyPi please confirm.

**Comment by keeth** [comment]
I'm waiting on this too.

**Comment by thedrow** [comment]
Please be patient.
The Celery 4.2 release took a lot of my free time.
I'll release it when I'll get the chance.

**Pull request merged**
