### PR TITLE
Fix transaction_isolation regression in MariaDB

### PR DESCRIPTION
**Pull request by ndido98**
Fixes again #83, since #84 introduced a regression in MariaDB, which as of 10.3 still uses the old `tx_isolation` name.

### CODE REVIEW

**Comment by auvipy** [comment]
make sure this wont create another regression!

**Comment by auvipy** [comment]
ping me if i forget to publish a minor release

**Comment by ndido98** [comment]
Ping!

**Comment by auvipy** [comment]
thanks for the ping

**Pull request merged**
